
spring.datasource.url=jdbc:mysql://localhost:3306/bluemoon?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=mat_khau_cua_cau
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
